module.exports = {
  heroes: [{
    name: 'Earthshaker',
    primary_atribute: 'strength',
    attack_type: 'melee',
    attack_range: 150,
    base_str: 22,
    base_agi: 12,
    base_int: 16,
    str_gain: 2.9,
    agi_gain: 1.4,
    int_gain: 1.8,
    base_hp: 200,
    base_hp_regen: 0.25,
    base_mana: 50,
    base_mana_regen: 0.01,
    BAT: 1.7,
    base_armor: 1,
    movespeed: 310,
    turn_rate: 0.9,
    base_damage_min: 24,
    base_damage_max: 34,
    day_vision: 1800,
    night_vision: 800,
    collision_size: 24,
    base_magic_resistance: 0.25,
    lore: "Like a golem or gargoyle, Earthshaker was one with the earth but now walks freely upon it. Unlike those other entities, he created himself through an act of will, and serves no other master. In restless slumbers, encased in a deep seam of stone, he became aware of the life drifting freely above him. He grew curious. During a season of tremors, the peaks of Nishai shook themselves loose of avalanches, shifting the course of rivers and turning shallow valleys into bottomless chasms. When the land finally ceased quaking, Earthshaker stepped from the settling dust, tossing aside massive boulders as if throwing off a light blanket. He had shaped himself in the image of a mortal beast, and named himself Raigor Stonehoof. He bleeds now, and breathes, and therefore he can die. But his spirit is still that of the earth; he carries its power in the magical totem that never leaves him. And on the day he returns to dust, the earth will greet him as a prodigal son.",
  },
  {
    name: 'Sven',
    primary_atribute: 'Strength',
    attack_type: 'melee',
    attack_range: 150,
    base_str: 23,
    base_agi: 21,
    base_int: 16,
    str_gain: 2.7,
    agi_gain: 2.0,
    int_gain: 1.3,
    base_hp: 200,
    base_hp_regen: 0.25,
    base_mana: 50,
    base_mana_regen: 0.01,
    BAT: 1.7,
    base_armor: 2,
    movespeed: 290,
    turn_rate: 0.6,
    base_damage_min: 41,
    base_damage_max: 43,
    day_vision: 1800,
    night_vision: 800,
    collision_size: 24,
    base_magic_resistance: 0.25,
    lore: "Sven is the bastard son of a Vigil Knight, born of a Pallid Meranth, raised in the Shadeshore Ruins. With his father executed for violating the Vigil Codex, and his mother shunned by her wild race, Sven believes that honor is to be found in no social order, but only in himself. After tending his mother through a lingering death, he offered himself as a novice to the Vigil Knights, never revealing his identity. For thirteen years he studied in his father's school, mastering the rigid code that declared his existence an abomination. Then, on the day that should have been his In-Swearing, he seized the Outcast Blade, shattered the Sacred Helm, and burned the Codex in the Vigil's Holy Flame. He strode from Vigil Keep, forever solitary, following his private code to the last strict rune. Still a knight, yes...but a Rogue Knight. He answers only to himself.",
  }],
};
